/* =============================================================================
 * ULTIMATE MOTORSPORT MANAGER
 * File: engine/raceAnimator.js
 * -----------------------------------------------------------------------------
 * RACE ANIMATOR — interpolates the timelines generated by RaceCalculator.
 * Takes the static simulation data and makes it fluid for the Canvas.
 * ========================================================================== */

class RaceAnimator {
    constructor() {
        this.timelines = []; // Raw data from engine.simulateEvent()
        this.raceType = "CircuitRace";
        this.durationMs = 0; // Total race duration to synchronize the end
        this.currentTimeMs = 0;
        this.speed = 1; // Speed multiplier (1x, 2x, 5x)
        this.isPlaying = false;
        this.animationFrameId = null;
        this.lastTimestamp = null;
        this.onUpdateCallback = null;
    }

    /** Loads the results of a simulation and prepares them for animation */
    loadEventData(eventData) {
        this.timelines = eventData.timelines || [];
        this.raceType = eventData.raceType;

        // Builds the set of retired drivers (DNF) from the final classification:
        // it's the only reliable way to distinguish a DNF (truncated timeline
        // mid-race) from a simply fast driver (finishes before the others but
        // has completed all laps).
        this.dnfDriverIds = new Set();
        if (Array.isArray(eventData.results)) {
            for (const r of eventData.results) {
                if (r.position === "DNF" || r.timeStr === "DNF") {
                    this.dnfDriverIds.add(r.driverId);
                }
            }
        }
        
        // Calculates the duration by finding the maximum time of who finished
        this.durationMs = 0;
        for (const t of this.timelines) {
            if (t.timeline.length > 0) {
                const lastT = t.timeline[t.timeline.length - 1].t;
                if (lastT > this.durationMs && lastT !== Infinity) {
                    this.durationMs = lastT;
                }
            }
        }
        this.currentTimeMs = 0;
        this.speed = 1;
    }

    /** Starts the animation loop */
    play() {
        if (this.isPlaying) return;
        this.isPlaying = true;
        this.lastTimestamp = performance.now();
        this._loop();
    }

    /** Pauses */
    pause() {
        this.isPlaying = false;
        if (this.animationFrameId) cancelAnimationFrame(this.animationFrameId);
    }

    /** Resets to the start */
    reset() {
        this.pause();
        this.currentTimeMs = 0;
        if (this.onUpdateCallback) this.onUpdateCallback(this.getState());
    }

    /** Sets the playback speed.
        When speed >= 60 ("Instant"), jumps straight to the end of the race. */
    setSpeed(s) {
        this.speed = s;
        if (s >= 60 && this.durationMs > 0) {
            this.currentTimeMs = this.durationMs;
            this.isPlaying = false;
            if (this.animationFrameId) cancelAnimationFrame(this.animationFrameId);
            if (this.onUpdateCallback) this.onUpdateCallback(this.getState());
        }
    }

    /** Registers who wants to receive position updates (the Renderer) */
    onUpdate(fn) { this.onUpdateCallback = fn; }

    /** Internal requestAnimationFrame loop */
    _loop() {
        if (!this.isPlaying) return;
        
        const now = performance.now();
        const deltaMs = (now - this.lastTimestamp) * this.speed; // Multiplies by speed
        this.lastTimestamp = now;

        this.currentTimeMs += deltaMs;

        // Stops the simulation at the end of the race
        if (this.currentTimeMs >= this.durationMs) {
            this.currentTimeMs = this.durationMs;
            this.isPlaying = false;
        }

        // Calculates the current positions and notifies the renderer
        if (this.onUpdateCallback) {
            this.onUpdateCallback(this.getState());
        }

        if (this.isPlaying) {
            this.animationFrameId = requestAnimationFrame(() => this._loop());
        }
    }

    /** Extracts the current coordinates (progress) for each driver */
    getState() {
        const state = {
            currentTimeMs: this.currentTimeMs,
            durationMs: this.durationMs,
            isFinished: !this.isPlaying && this.currentTimeMs >= this.durationMs,
            drivers: []
        };

        for (const driverData of this.timelines) {
            const tl = driverData.timeline;
            if (tl.length === 0) continue;

            let currentProgress = 0;
            let lap = 1;

            // Finds the last point of the timeline earlier than currentTimeMs
            let i = 0;
            while (i < tl.length - 1 && tl[i + 1].t <= this.currentTimeMs) {
                i++;
            }

            const currentPoint = tl[i];
            const nextPoint = tl[i + 1];

            if (nextPoint) {
                // Linear interpolation between two points of the timeline
                const segmentDuration = nextPoint.t - currentPoint.t;
                const segmentProgress = segmentDuration > 0 
                    ? (this.currentTimeMs - currentPoint.t) / segmentDuration 
                    : 0;
                
                // Interpolates the progress (handles both laps and linear SS)
                currentProgress = currentPoint.progress + (nextPoint.progress - currentPoint.progress) * segmentProgress;
            } else {
                currentProgress = currentPoint.progress;
            }

            // For circuit races, the progress is cumulative (1, 2, 3...).
            // For the canvas we only need the position within the current lap (0..1)
            let trackProgress = currentProgress;
            if (this.raceType === "CircuitRace" || this.raceType === "EnduranceRace") {
                lap = Math.floor(currentProgress);
                trackProgress = currentProgress % 1; // From 0 to 1 within the lap
                if (trackProgress < 0) trackProgress += 1; // Corrects start
            }

            // Determines if the driver is retired (DNF) by consulting the set
            // built in loadEventData from the final classification.
            const isDNF = this.dnfDriverIds && this.dnfDriverIds.has(driverData.driverId);

            // For DNFs: freezes the driver at the last known position of their
            // timeline (where they retired), so the renderer can show them
            // as a stationary gray dot on the track instead of making them disappear.
            let finalProgress = trackProgress;
            if (isDNF) {
                const last = tl[tl.length - 1];
                if (this.raceType === "CircuitRace" || this.raceType === "EnduranceRace") {
                    finalProgress = (last.progress % 1 + 1) % 1;
                } else {
                    finalProgress = last.progress;
                }
            }

            state.drivers.push({
                id: driverData.driverId,
                name: driverData.driver,
                teamId: driverData.teamId,
                color: driverData.color,
                trackProgress: finalProgress,
                lap: lap,
                finished: !isDNF,
                dnf: isDNF
            });
        }

        return state;
    }
}

// Global exposure
if (typeof window !== "undefined") window.RaceAnimator = RaceAnimator;
if (typeof module !== "undefined" && module.exports) module.exports = { RaceAnimator };